### ISSUE TITLE
Latest version 1.8.1 of webpack-dev-middleware breaks manifest retrieval

### ISSUE THREAD

**Issue by mipearson** [unindented/stats-webpack-plugin#11]
Hi,

Originally discovered at https://github.com/mipearson/webpack-rails/issues/58, then confirmed by our team at Marketplacer.

Webpack config:

```
  output: {
    publicPath: '/webpack/',
...

  plugins: [
    new StatsPlugin('manifest.json', {
      // We only need assetsByChunkName
      chunkModules: false,
      source: false,
      chunks: false,
      modules: false,
      assets: true
    }),
...
```

With webpack-dev-middleware 1.8.1, `/webpack/manifest.json` is a 404. With 1.7.0, it contains the manifest as expected.

Writing out the manifest.json to the filesystem works as normal.

I'm not sure if this is a bug with the middleware itself or with how stats-webpack-plugin interacts with the middleware.

**Comment by francistm** [comment]
+1
Got the same issue

**Comment by unindented** [comment]
I have no idea what could be going on. Have you had a chance to look into it further?
