### ISSUE TITLE
Make stats available directly in js

### ISSUE THREAD

**Issue by jescalan** [unindented/stats-webpack-plugin#19]
So with this plugin, an extra request is required to fetch the stats file's contents from the client side, if I'm not mistaken, but this step could easily be eliminated by injecting the stats as a constant directly to the javascript like [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) does. 

Just curious whether you have thought about this or have any opinions on benefits, drawbacks, etc. If you are interested, I'd be happy to submit a PR for this feature when I have a moment.

**Comment by unindented** [comment]
How can you inject the final stats of a bundle in a file that you are bundling? The moment that you inject the stats, you'll be changing the bundle, which will mean the stats will change, which means the bundle will change, ad infinitum...

**Comment by unindented** [comment]
I think this issue doesn't make sense, but feel free to reopen if you have a better explanation.
