### ISSUE TITLE
Second compile doesn't clean the error and warning properties

### ISSUE THREAD

**Issue by monvillalon** [unindented/stats-webpack-plugin#20]
The warning and error properties of the stats result
of the previous compilation and merged into the
new stats instead of reflecting the new values

I think it was introduced here: 91fb22f0f7efcdaacee239cef81127dba712fdbb

I solved it in my local copy by changing
```
        var stats = compilation.getStats().toJson(options)
        cache = _.merge(cache, stats)  // <<< MERGE ARRAYS
        result = JSON.stringify(cache)
        return result
```

to 

```
        var stats = compilation.getStats().toJson(options)
        cache = _.assign(cache, stats) // <<< DON'T MERGE ARRAYS
        result = JSON.stringify(cache)
        return result
```

but don't know if this breaks something else. As far as I can deduce, every compilation event
emits the full value of every property even if some are missing, but I might be wrong and
errors and warnings should be handled as a special case

```
        var stats = compilation.getStats().toJson(options)
        cache = _.merge(cache, stats) 
        // === DON'T MERGE ERRORS AND WARNINGS
        if (stats.errors) cache.errors = stats.errors
        if (stats.warnings) cache.warnings = stats.warnings
        // === DON'T MERGE ERRORS AND WARNINGS
        result = JSON.stringify(cache)
        return result
```

I'll write a merge request but I first would like to have your input as to what
approach to take.

Thanks

**Comment by monvillalon** [comment]
Found the related issue for the commit
https://github.com/unindented/stats-webpack-plugin/issues/13

Because of this think option 3, treating the errors and warnings as a special case
is the smarter choice.  But further research has to be done if this
happens with the other properties.

**Comment by unindented** [comment]
Fixed by https://github.com/unindented/stats-webpack-plugin/pull/21
