### ISSUE TITLE
Incorrect peer dependency webpack 3

### ISSUE THREAD

**Issue by KlonD90** [unindented/stats-webpack-plugin#23]
I installed webpack 3 and got an warning from this package.

warning "stats-webpack-plugin@0.6.1" has incorrect peer dependency "webpack@^1.0||^2.1.0-beta||^2.2.0-rc".

Can i just ignore it? Or it can do something bad for me?

**Comment by modosc** [comment]
see #24

**Comment by rhys-vdw** [comment]
@modosc Actually #24 doesn't answer the question of whether the warning can be ignored.

**Comment by modosc** [comment]
i've been using it in production with webpack3 for at least a month without issue so anecdotally it's safe to ignore. ideally #24 gets merged and the warning goes away.

**Comment by unindented** [comment]
Fixed with latest version `v0.6.2`.
