### ISSUE TITLE
Feature request: output filename

### ISSUE THREAD

**Issue by mnpenner** [unindented/stats-webpack-plugin#6]
This plugin always seems to dump the stats file in `output.path` even when I give it an absolute file path.

I have my `output.path` pointed to a public assets directory, but I don't want my stats file dumped in there too because there's no need for me to serve this file to the public.

This could be solved in a number of ways:

1. Respect absolute paths; don't join it with `ouput.path`
2. Add an `outputDirectory` option
3. Add a `filename` option, similar to `CommonsChunkPlugin` that overrides the `path` option

**Comment by unindented** [comment]
This has already been discussed here: https://github.com/unindented/stats-webpack-plugin/issues/4

Try using a relative path, e.g. `../stats.json`.
