### ISSUE TITLE
Process out of memory error when updating from 0.2.1 to 0.3.1

### ISSUE THREAD

**Issue by amccarthyMatchbook** [unindented/stats-webpack-plugin#8]
Updated version from 0.2.1 to 0.3.1.
Using the plugin as part of my build process, when I run the process now I am getting a process out of memory error.

<--- Last few GCs --->

   88269 ms: Scavenge 1414.7 (1460.5) -> 1414.7 (1460.5) MB, 0.7 / 0 ms (+ 1.9 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   88328 ms: Mark-sweep 1414.7 (1460.5) -> 1391.3 (1440.0) MB, 58.8 / 0 ms (+ 50.2 ms in 15 steps since start of marking, biggest step 14.5 ms) [last resort gc].
   88392 ms: Mark-sweep 1391.3 (1440.0) -> 1391.2 (1440.0) MB, 64.1 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x177b552e3ac1 <JS Object>
    2: /* anonymous */(aka /* anonymous */) [/Users/test/test-ui/node_modules/webpack/lib/NormalModuleFactory.js:58] [pc=0xe3ebfe0c150] (this=0x177b55204189 <undefined>,err=0x177b55204101 <null>,result=0x3c701fc4aa9 <an Object with map 0x16c3128da09>)
    3: applyPluginsAsyncWaterfall [/Users/test/test-ui/node_modules/tapable/lib/Tapable.js:~74] [pc=0xe3ebfe90efe] (this=...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

**Comment by amccarthyMatchbook** [comment]
My fault, found the issue, I'm using node 5.6.0, when I set the node version to 4.2.1 it works fine.

**Comment by amccarthyMatchbook** [comment]
Looks like it's an issue with the version of node.
I'm using 5.6.0 when I switched to 4.2.1 it works fine.

**Comment by unindented** [comment]
Thanks for looking into it. I have seen that error before when calling `getStats().toJson()`, but there's nothing I can do on my side...

I've noticed that the bigger the stats object, the more likely it is to crash, so I try to exclude the `node_modules` folder, and any others I'm not interested in.

**Comment by amccarthyMatchbook** [comment]
Hey thanks for the reply. Excluding the node_modules folder also, still get the process out of memory error when using node 5.6.0

**Comment by unindented** [comment]
If you are ok with it, I'll close the ticket, as I'm pretty sure this issue is out of my control...

**Comment by amccarthyMatchbook** [comment]
Yes please close the ticket. 
Sorry my fault, I checked my web-pack config and I hadn't excluded the node_modules folder.
Thanks for the help it's is working perfect with 5.6.0 now!
